In [1]:
import pandas as pd
import numpy as np
data = pd.read_excel('school_enroll_unit_admission.xlsx')
data.head(5) #读取数据

,id,enroll_unit_id,school_id,stu_province_id,enroll_year,batch_name,admission_count,min_score,min_score_rank,min_score_diff,avg_score,avg_score_rank,max_score,max_score_rank,create_time,update_time,wenli
0,1,52ac2e9a747aec013fcf5190,52ac2e9a747aec013fcf5190,510000000000,2020,本科第一批,NaN,646,1,119.0,NaN,NaN,NaN,NaN,2021-03-21 17:30:04,2021-03-21 17:30:04,1
1,2,52ac2e9a747aec013fcf5190,52ac2e9a747aec013fcf5190,510000000000,2019,本科第一批,23.0,658,38,118.0,NaN,NaN,NaN,NaN,2021-03-21 17:30:05,2021-03-21 17:30:05,1
2,3,52ac2e9a747aec013fcf5190,52ac2e9a747aec013fcf5190,510000000000,2018,本科第一批,24.0,642,39,89.0,648.0,37.0,663.0,32.0,2021-03-21 17:30:05,2021-03-21 17:30:05,1
3,4,52ac2e9a747aec013fcf5190,52ac2e9a747aec013fcf5190,510000000000,2017,本科第一批,NaN,650,25,113.0,NaN,NaN,668.0,10.0,2021-03-21 17:30:05,2021-03-21 17:30:05,1
4,5,52ac2e9a747aec013fcf5190,52ac2e9a747aec013fcf5190,510000000000,2020,本科第一批,NaN,695,71,166.0,NaN,NaN,NaN,NaN,2021-03-21 17:30:06,2021-03-21 17:30:06,2

In [2]:
data2 = data[['enroll_year','school_id','min_score']]
data2.head()

   enroll_year                 school_id  min_score
0         2020  52ac2e9a747aec013fcf5190        646
1         2019  52ac2e9a747aec013fcf5190        658
2         2018  52ac2e9a747aec013fcf5190        642
3         2017  52ac2e9a747aec013fcf5190        650
4         2020  52ac2e9a747aec013fcf5190        695

In [3]:
import matplotlib.pyplot as plt  #引入绘图库
from sklearn.model_selection import train_test_split #数据拆分
from sklearn.linear_model import LinearRegression

In [7]:
data4 =data2.drop_duplicates(subset=['enroll_year','school_id'], keep='first', inplace=False)

In [8]:
index_series = data4.set_index([ "school_id","enroll_year"])["min_score"]
new_df = index_series.unstack()
new_df.isnull().sum()

enroll_year
2017    197
2018    186
2019    248
2020    102
dtype: int64

In [9]:
new_df.head()

enroll_year                2017   2018   2019   2020
school_id
01786a532699c7c3e814d741    NaN    NaN    NaN  150.0
14488c097563ac874c2d2f07    NaN    NaN    NaN  150.0
2194e3ee37c308cd6229a5d4    NaN    NaN    NaN  492.0
28a83fd2eab9fefa4f9ff417    NaN    NaN    NaN  150.0
52ac2e97747aec013fcf49a0  367.0  190.0  318.0  150.0

In [10]:
new_df = new_df.rename_axis(columns=None)
new_df = new_df.reset_index()
new_df.head()

                  school_id   2017   2018   2019   2020
0  01786a532699c7c3e814d741    NaN    NaN    NaN  150.0
1  14488c097563ac874c2d2f07    NaN    NaN    NaN  150.0
2  2194e3ee37c308cd6229a5d4    NaN    NaN    NaN  492.0
3  28a83fd2eab9fefa4f9ff417    NaN    NaN    NaN  150.0
4  52ac2e97747aec013fcf49a0  367.0  190.0  318.0  150.0

In [11]:
new_df=new_df.dropna(axis=0,how='any')
new_df=new_df.drop(new_df[new_df[2020]<=300].index)
new_df=new_df.drop(new_df[new_df[2017]<=300].index)
new_df=new_df.drop(new_df[new_df[2018]<=300].index)
new_df=new_df.drop(new_df[new_df[2019]<=300].index)

In [12]:
x=new_df.iloc[:,1:4]
x2 = x.values.reshape(-1,1)
y=new_df.iloc[:,4:].values.reshape(-1,1)
x2

array([[571.],
       [584.],
       [582.],
       ...,
       [386.],
       [524.],
       [519.]])

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25)

In [14]:
linreg2 = LinearRegression() #调用最小2乘法的模型
linreg2.fit(X_train,  y_train)
print(linreg2.coef_)
print(linreg2.intercept_)
#模型训练过程

[[0.12422307 0.16529378 0.61679581]]
[38.36418675]

In [15]:
y =0.08x1+0.17x2+0.64x3+41

SyntaxError: invalid syntax (<ipython-input-15-f719a39376fc>, line 1)

In [16]:
linreg2.score(X_test,y_test) #模型准确率96%

0.9521201047135912

In [17]:
x4=new_df.iloc[:,2:5]
x5 = linreg2.predict(x4)
x6 =np.ravel(x5)
new_df[2021] =x6
new_df

                     school_id   2017   2018   2019   2020        2021
6     52ac2e97747aec013fcf49a3  571.0  584.0  582.0  569.0  558.068255
7     52ac2e97747aec013fcf49a4  537.0  552.0  540.0  515.0  513.843805
8     52ac2e97747aec013fcf49a5  490.0  515.0  519.0  500.0  496.524444
9     52ac2e97747aec013fcf49a6  572.0  585.0  583.0  570.0  558.974568
10    52ac2e97747aec013fcf49a8  480.0  515.0  517.0  503.0  498.044244
11    52ac2e97747aec013fcf49a9  470.0  499.0  477.0  466.0  466.623479
12    52ac2e97747aec013fcf49aa  521.0  542.0  529.0  518.0  512.633730
13    52ac2e97747aec013fcf49ab  493.0  514.0  496.0  482.0  481.496140
14    52ac2e97747aec013fcf49ac  524.0  542.0  529.0  518.0  512.633730
16    52ac2e97747aec013fcf49af  472.0  495.0  475.0  463.0  463.945612
17    52ac2e97747aec013fcf49b0  600.0  608.0  610.0  598.0  583.564913
18    52ac2e97747aec013fcf49b1  521.0  543.0  527.0  513.0  509.343386
19    52ac2e97747aec013fcf49b4  455.0  472.0  451.0  449.0  448.486289
22    52ac2e97747aec013fcf49b9  407.0  443.0  431.0  436.0  433.559599
23    52ac2e97747aec013fcf49ba  518.0  541.0  520.0  508.0  504.853904
24    52ac2e97747aec013fcf49bc  503.0  527.0  509.0  494.0  492.661409
26    52ac2e97747aec013fcf49be  454.0  483.0  487.0  468.0  467.522439
28    52ac2e97747aec013fcf49c1  518.0  538.0  526.0  514.0  509.173773
31    52ac2e97747aec013fcf49c4  582.0  599.0  600.0  591.0  576.476397
32    52ac2e97747aec013fcf49c5  478.0  501.0  478.0  461.0  463.953240
33    52ac2e97747aec013fcf49c6  509.0  531.0  519.0  510.0  504.679972
35    52ac2e97747aec013fcf49c9  582.0  585.0  584.0  574.0  561.607045
36    52ac2e97747aec013fcf49ca  489.0  549.0  525.0  518.0  512.842116
38    52ac2e97747aec013fcf49cd  477.0  505.0  485.0  477.0  475.475922
39    52ac2e97747aec013fcf49cf  480.0  502.0  483.0  474.0  472.922277
40    52ac2e97747aec013fcf49d0  535.0  555.0  542.0  527.0  521.948611
41    52ac2e97747aec013fcf49d1  581.0  594.0  595.0  583.0  570.094446
42    52ac2e97747aec013fcf49d2  527.0  546.0  533.0  522.0  516.258980
44    52ac2e97747aec013fcf49d7  596.0  604.0  607.0  597.0  581.955344
46    52ac2e97747aec013fcf49da  524.0  543.0  534.0  517.0  512.967626
...                        ...    ...    ...    ...    ...         ...
2019  5550299306d8da7897169bc6  527.0  543.0  531.0  522.0  515.555723
2021  5550299506d8da7897169bc8  393.0  446.0  437.0  439.0  436.774418
2022  5550299806d8da7897169bca  448.0  459.0  445.0  443.0  442.178852
2024  5550299b06d8da7897169bcc  473.0  494.0  476.0  447.0  454.117950
2031  555029a506d8da7897169bd4  386.0  441.0  413.0  427.0  424.784702
2032  555029a506d8da7897169bd5  420.0  464.0  313.0  417.0  404.944497
2036  555029a806d8da7897169bd9  302.0  422.0  395.0  410.0  408.963647
2041  555029b406d8da7897169be5  353.0  414.0  413.0  412.0  412.178742
2045  5673760ed6d9f512540c5bef  462.0  494.0  473.0  459.0  461.023618
2047  5673760ed6d9f512540c5bf3  312.0  381.0  372.0  390.0  387.732828
2051  5673760ed6d9f512540c5bff  341.0  474.0  458.0  452.0  451.742179
2059  5673760fd6d9f512540c5c19  500.0  543.0  548.0  522.0  518.365718
2060  56f3bb997187f06e544c8aad  672.0  681.0  698.0  689.0  663.307468
2061  56f3bb997187f06e544c8b00  536.0  556.0  543.0  528.0  522.854924
2062  570b4d7ad6d9f53ec09604d7  663.0  673.0  692.0  677.0  653.920372
2065  570c7212df6537f0c9a6f0f7  613.0  618.0  623.0  609.0  593.740717
2066  570c7212df6537f0c9a6f0f8  566.0  603.0  613.0  598.0  583.439679
2067  570c7212df6537f0c9a6f0f9  592.0  635.0  656.0  646.0  624.128649
2068  570c7212df6537f0c9a6f0fb  561.0  574.0  573.0  566.0  553.487993
2069  57345608d6d9f566d32dfff3  509.0  535.0  519.0  507.0  503.326476
2071  57398f07d6d9f5564965fa28  549.0  566.0  527.0  547.0  533.171574
2072  57398f07d6d9f5564965fa29  582.0  589.0  592.0  577.0  565.276675
2075  5767a72e4cd81dcc0972c507  342.0  418.0  351.0  390.0  388.857912
2076  5767a72e4cd81dcc0972c508  510.0  528.0  506.0  489.0  489.205771
2094  58b5434c7cadef952da48fb8  544.0  562.0  554.0  548.0  537.754410
2096  593f97cdad74867240c8384a  611.0  615.0  621.0  608.0  592.420664
2098  593f97f0ad74867240c83930  393.0  438.0  417.0  433.0  428.773983
2100  593f980ead74867240c8398d  340.0  403.0  354.0  369.0  374.537736
2101  593f9812ad74867240c839af  544.0  590.0  596.0  529.0  536.455874
2117  594ae39bad74860e87e169f3  386.0  524.0  519.0  508.0  502.576818

[1191 rows x 6 columns]

In [14]:
c1=new_df.iloc[:,1:4]
c2 = linreg2.predict(c1)
c3 =np.ravel(c2)
new_df[2020_1] =x6
new_df

,school_id,2017,2018,2019,2020,2021,20201
6,52ac2e97747aec013fcf49a3,571.0,584.0,582.0,569.0,556.472319,556.472319
7,52ac2e97747aec013fcf49a4,537.0,552.0,540.0,515.0,511.802733,511.802733
8,52ac2e97747aec013fcf49a5,490.0,515.0,519.0,500.0,495.512367,495.512367
9,52ac2e97747aec013fcf49a6,572.0,585.0,583.0,570.0,557.371537,557.371537
10,52ac2e97747aec013fcf49a8,480.0,515.0,517.0,503.0,497.070939,497.070939
11,52ac2e97747aec013fcf49a9,470.0,499.0,477.0,466.0,464.894809,464.894809
12,52ac2e97747aec013fcf49aa,521.0,542.0,529.0,518.0,510.952156,510.952156
13,52ac2e97747aec013fcf49ab,493.0,514.0,496.0,482.0,479.747350,479.747350
14,52ac2e97747aec013fcf49ac,524.0,542.0,529.0,518.0,510.952156,510.952156
16,52ac2e97747aec013fcf49af,472.0,495.0,475.0,463.0,462.300172,462.300172
17,52ac2e97747aec013fcf49b0,600.0,608.0,610.0,598.0,581.978630,581.978630
18,52ac2e97747aec013fcf49b1,521.0,543.0,527.0,513.0,507.467114,507.467114
19,52ac2e97747aec013fcf49b4,455.0,472.0,451.0,449.0,447.198952,447.198952
22,52ac2e97747aec013fcf49b9,407.0,443.0,431.0,436.0,432.994004,432.994004
23,52ac2e97747aec013fcf49ba,518.0,541.0,520.0,508.0,502.842988,502.842988
24,52ac2e97747aec013fcf49bc,503.0,527.0,509.0,494.0,490.796985,490.796985
26,52ac2e97747aec013fcf49be,454.0,483.0,487.0,468.0,466.737386,466.737386
28,52ac2e97747aec013fcf49c1,518.0,538.0,526.0,514.0,507.536300,507.536300
31,52ac2e97747aec013fcf49c4,582.0,599.0,600.0,591.0,574.985053,574.985053
32,52ac2e97747aec013fcf49c5,478.0,501.0,478.0,461.0,462.030817,462.030817
33,52ac2e97747aec013fcf49c6,509.0,531.0,519.0,510.0,503.162378,503.162378
35,52ac2e97747aec013fcf49c9,582.0,585.0,584.0,574.0,560.113361,560.113361
36,52ac2e97747aec013fcf49ca,489.0,549.0,525.0,518.0,510.774086,510.774086
38,52ac2e97747aec013fcf49cd,477.0,505.0,485.0,477.0,473.853160,473.853160
39,52ac2e97747aec013fcf49cf,480.0,502.0,483.0,474.0,471.336522,471.336522
40,52ac2e97747aec013fcf49d0,535.0,555.0,542.0,527.0,520.081185,520.081185
41,52ac2e97747aec013fcf49d1,581.0,594.0,595.0,583.0,568.568358,568.568358
42,52ac2e97747aec013fcf49d2,527.0,546.0,533.0,522.0,514.549029,514.549029
44,52ac2e97747aec013fcf49d7,596.0,604.0,607.0,597.0,580.483380,580.483380
46,52ac2e97747aec013fcf49da,524.0,543.0,534.0,517.0,511.295038,511.295038
...,...,...,...,...,...,...,...
2019,5550299306d8da7897169bc6,527.0,543.0,531.0,522.0,513.952996,513.952996
2021,5550299506d8da7897169bc8,393.0,446.0,437.0,439.0,436.234709,436.234709
2022,5550299806d8da7897169bca,448.0,459.0,445.0,443.0,441.257646,441.257646
2024,5550299b06d8da7897169bcc,473.0,494.0,476.0,447.0,452.159962,452.159962
2031,555029a506d8da7897169bd4,386.0,441.0,413.0,427.0,423.817886,423.817886
2032,555029a506d8da7897169bd5,420.0,464.0,313.0,417.0,401.108176,401.108176
2036,555029a806d8da7897169bd9,302.0,422.0,395.0,410.0,408.194162,408.194162
2041,555029b406d8da7897169be5,353.0,414.0,413.0,412.0,412.108871,412.108871
2045,5673760ed6d9f512540c5bef,462.0,494.0,473.0,459.0,459.299332,459.299332
2047,5673760ed6d9f512540c5bf3,312.0,381.0,372.0,390.0,388.028755,388.028755
2051,5673760ed6d9f512540c5bff,341.0,474.0,458.0,452.0,450.542674,450.542674
2059,5673760fd6d9f512540c5c19,500.0,543.0,548.0,522.0,517.030283,517.030283
2060,56f3bb997187f06e544c8aad,672.0,681.0,698.0,689.0,661.860438,661.860438
2061,56f3bb997187f06e544c8b00,536.0,556.0,543.0,528.0,520.980404,520.980404
2062,570b4d7ad6d9f53ec09604d7,663.0,673.0,692.0,677.0,652.467920,652.467920
2065,570c7212df6537f0c9a6f0f7,613.0,618.0,623.0,609.0,592.154064,592.154064
2066,570c7212df6537f0c9a6f0f8,566.0,603.0,613.0,598.0,582.131683,582.131683
2067,570c7212df6537f0c9a6f0f9,592.0,635.0,656.0,646.0,623.141076,623.141076
2068,570c7212df6537f0c9a6f0fb,561.0,574.0,573.0,566.0,552.142566,552.142566
2069,57345608d6d9f566d32dfff3,509.0,535.0,519.0,507.0,501.553772,501.553772
2071,57398f07d6d9f5564965fa28,549.0,566.0,527.0,547.0,531.027962,531.027962
2072,57398f07d6d9f5564965fa29,582.0,589.0,592.0,577.0,563.794099,563.794099
2075,5767a72e4cd81dcc0972c507,342.0,418.0,351.0,390.0,387.113388,387.113388
2076,5767a72e4cd81dcc0972c508,510.0,528.0,506.0,489.0,487.130925,487.130925
2094,58b5434c7cadef952da48fb8,544.0,562.0,554.0,548.0,536.243620,536.243620
2096,593f97cdad74867240c8384a,611.0,615.0,621.0,608.0,590.917830,590.917830
2098,593f97f0ad74867240c83930,393.0,438.0,417.0,433.0,428.149165,428.149165
2100,593f980ead74867240c8398d,340.0,403.0,354.0,369.0,373.042209,373.042209
2101,593f9812ad74867240c839af,544.0,590.0,596.0,529.0,533.866486,533.866486
2117,594ae39bad74860e87e169f3,386.0,524.0,519.0,508.0,501.335977,501.335977

20201 就是预测2020年的 与可以比较接近有些比较不准

In [24]:
new_df.to_excel('new_df.xlsx')